site_name: Chessfield Documentation
site_url: https://unicolored.github.io/chessfield/
repo_url: https://github.com/unicolored/chessfield
site_description: A JavaScript library for chessboard generation and manipulation
site_author: unicolored
theme:
  name: material # Use mkdocs-material theme
  palette:
    primary: teal # Customize colors
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
